### ISSUE TITLE
Spreading Forth 

### ISSUE THREAD

**Issue by xieyuheng** [ForthHub/discussion#10]
---

---

Spreading Forth

---

we can do something like << forth dimensions >>

to publish readings about forth in html and pdf
- interviews
- articles
- reports
- ideas
- compares of features & syntaxes & semantic of variety of forth dialects

and interfacing our publishes with a good database from our web page

---

I think it won't require any very hard works to start

and 

<< Spreading Forth >>

<< Forth Spreading >>

<< Forth ideas >>

are my proposed names :)

I am not good at English 

so

may you suggest more

---

---

**Comment by jamesbowman** [comment]
Very keen on this idea. Maybe restart "Forth Dimensions"?

I would definitely be willing to make regular submissions. The German version is still running, and perhaps would also allow us to translate some of their articles?

http://www.forth-ev.de/filemgmt/viewcat.php?cid=2

**Comment by lowfatcomputing** [comment]
I too would very much like to see The Forth Dimensions Magazine in print again. The German Forth Gesellschaft has *Vierte Dimension* and the UKFIG has the *Forthwrite Magazine*. Of these I think *Vierte Dimension* has the most content and is the most active.

http://www.figuk.plus.com/articles.htm
http://soton.mpeforth.com/flag/jfar/

We could put it in print without the risks of a printing a minimum sized batch by using a [Print On Demand (POD)](https://en.wikipedia.org/wiki/Print_on_demand) service such as [MagCloud](http://www.magcloud.com/).

**Comment by Mat2** [comment]
I think that is a very good idea which I would support though translation of Vierte Dimension articles, if that cause no copyright violation. Who can and want to take over the organization of such online magazine ?

**Comment by aseaday** [comment]
I could translate it int ochinese and offer some help.

________________________________
发件人: Matthias Schirm <notifications@github.com>
发送时间: 2016年3月21日 21:03:15
收件人: ForthHub/discussion
主题: Re: [discussion] Spreading Forth (#10)


I think that is a very good idea which I would support though translation of Vierte Dimension articles, if that cause no copyright violation. Who can and want to take over the organization of such online magazine ?

―

**Comment by jjonethal** [comment]
@forthy42 how about the copyrights for 4d ?

**Comment by julian-becker** [comment]
Thumbs up for a FORTH online magazine! I could also help with German translations if needed

**Comment by Mat2** [comment]
I've written an e-mail request to the Forth Gesellschaft and hope to get an answer soon.

**Comment by GeraldWodni** [comment]
@Mat2 I'm sure you'll get an answer soon. Our annual meeting is next Weekend in Augsburg, I'll make sure to bring the matter to attention. So I guess you can expect an official answer the week afterwards.

**Comment by forthy42** [comment]
The current copyright status of Vierte Dimension is that you are allowed to reprint and translate the articles with proper citation of the origin. We will discuss that matter on our meeting in person, because our intention is to get more authors, more articles, and more readers.

Of course, I'm all busy now with preparing the meeting ;-).

**Comment by Mat2** [comment]
I plan preparing a temporary web site at end of next week and invite everyone who can and want help in an online edition to contact me.

**Comment by xieyuheng** [comment]
closing old issues :)
