### ISSUE TITLE
uni-wiki

### ISSUE THREAD

**Issue by xieyuheng** [ForthHub/discussion#11]
I have just created a wiki index in reddit ::

http://www.reddit.com/r/Forth/wiki/index

if you agree that reddit is a better please to host wiki, 
then we can have a link from Github's wiki to reddit's.

discussion can also be done here ::

http://www.reddit.com/r/Forth/comments/3684kx/our_forth_wiki_need_more_writers/

**Comment by larsbrinkhoff** [comment]
Good job with the new wiki!

**Comment by jjonethal** [comment]
The categorization on the implementations page points to a wrong page with my Firefox mobile

**Comment by xieyuheng** [comment]
@jjonethal
you can edit the wiki

**Comment by xieyuheng** [comment]
closing old issues :)
