### ISSUE TITLE
Star me ForthStar!

### ISSUE THREAD

**Issue by laheadle** [ForthHub/discussion#23]
Hey ForthStar!

https://github.com/laheadle/stackler

**Comment by larsbrinkhoff** [comment]
ForthStars are primarily for repositories with a significant amount of Forth code.  Rewrite stackler in Forth, and your're in!

**Comment by laheadle** [comment]
Ha! ok.

**Comment by larsbrinkhoff** [comment]
You're welcome to the organization, though!
