### ISSUE TITLE
forks in ForthHub

### ISSUE THREAD

**Issue by ruv** [ForthHub/discussion#34]
What is a reason to have so many forks here? 

For example, what is the intended use for [ffl](/ForthHub/ffl)?

- If it is just a mirror, it should be kept in [sync with origin](https://help.github.com/articles/syncing-a-fork/) in fast-forward mode.
- If its intention to make pull-requests into origin (i.e. use the fork in ForthHub instead of creating own fork), participants should have access for that.
- If it is just a backup copy, it should probably be in [Archive team](/orgs/ForthHub/teams/archive/repositories).

**Comment by larsbrinkhoff** [comment]
It was my intentention that the forks would bade my the [Libraries and Tools] team:
https://github.com/ForthHub/discussion/issues/17

Now I recognise that this was probably a bad idea, and it would be better to use a wiki page.

**Comment by ruv** [comment]
Oh, I see.  Perhaps, the outdated repositories can be removed without any losses.

**Comment by rogerlevy** [comment]
I was also confused by this.  At first I thought it was cool, then I realized that it just fragments things.  I vote for removing them and making it a list in the Wiki.
