### ISSUE TITLE
EuroForth 2017 invitation

### ISSUE THREAD

**Issue by GeraldWodni** [ForthHub/discussion#42]
Dear Forthers,

*EuroForth brings together researchers and practitioners from the Forth community* (quote from the [EuroForth Website](http://www.complang.tuwien.ac.at/anton/euroforth/)).
This year's EuroForth will be held in Bad Vöslau near Vienna.

Papers are solicited on all aspects of Forth (applications, implementations, extensions, etc.) and related topics. Here is the [Call for papers](http://www.complang.tuwien.ac.at/anton/euroforth/ef17/cfp.html).

We (regular EuroForth attendants) would love to meet people from the ForthHub in person, and as I have the feeling that lots of ForthHub members are not following comp.lang.forth or other ancient technologies, I wanted to reach out to you directly.

Before the EuroForth conference the [Forth Standard](http://forth-standard.org/) Meeting takes place in which the language and its compilation techniques are discussed in detail.

In case you want to merge a vacation and the conference: a separate partner track which includes lots of sightseeing in Vienna will also be provided, so bring your partners ;)

More details and the registration Form can be found on: http://euro.theforth.net/

Regards,
Gerald Wodni

**Comment by 0xae** [comment]
This is amazing, thank you so much.
i would love to go to a  FORTH conference.

**Comment by cwpjr** [comment]
Latest i've seen.
http://euro.theforth.net/

**Comment by RickCarlino** [comment]
I just registered! Anyone else from ForthHub planning to attend? Look forward to it.

**Comment by larsbrinkhoff** [comment]
I'm considering it.

**Comment by GeraldWodni** [comment]
So far we got attendees from the following countries:

China (Hong Kong), Estonia, Germany, Great Britain, South Africa, United States & Austria (obviously ;) )

I'd love to extend that list with _your_ country, or `1+`/`2+` the counter on existing ones!
I'll keep the [registration](http://euro.theforth.net) open as long as possible, but I'm afraid that the prices might increase a bit for late bookers, as the location will want some definitive numbers rather soon to make best use of their room allocation and provide an incentive. So book soon ;)
