### ISSUE TITLE
adding avrforth

### ISSUE THREAD

**Issue by kristianlm** [ForthHub/discussion#60]
Hi!

I've been looking at [avrforth](http://krue.net/avrforth/) for a while now and I think it's a very elegant and impressive piece of work. It certainly deserves to be in this on the list somewhere, no?

**Comment by larsbrinkhoff** [comment]
Yes it does!

**Comment by kristianlm** [comment]
Like [this](https://github.com/ForthHub/wiki/pull/2)?
