### ISSUE TITLE
ForthStar for Forth implementations

### ISSUE THREAD

**Issue by ruv** [ForthHub/discussion#72]
Is it implied for [ForthStar](https://github.com/ForthStar?tab=stars) to put stars on Forth implementations?

Sometimes Forth implementations in other languages don't contain a code in Forth at all.
For example, Forth in Rust:

- https://github.com/chengchangwu/rtforth
- https://github.com/zack-bitcoin/forth-in-rust

For the moment they are not starred by ForthStar. Is a sense to star them?

**Comment by larsbrinkhoff** [comment]
I'm the person behind ForthStar.

No, I don't star all Forth implementations.  The purpose of ForthStar is to star repositories with a significant amount of Forth code.

**Comment by ruv** [comment]
I would suggest adding this purpose into the Profile/Bio of ForthStar, i.e. "The purpose of ForthStar is to star repositories with a significant amount of Forth code".

**Comment by larsbrinkhoff** [comment]
I'll do that.  But a little shorter.
