### ISSUE TITLE
a github page of this org is needed! [or not?]

### ISSUE THREAD

**Issue by xieyuheng** [ForthHub/discussion#8]
and more wiki s should be added
to form a richer community :) IMHO

**Comment by larsbrinkhoff** [comment]
You're welcome to push to https://github.com/ForthHub/forthhub.github.io!

**Comment by xieyuheng** [comment]
a framework is pushed
  * it is based on my site :
    http://the-little-language-designer.github.io/
  * feel free to re-design anything of it
  * personally
    I will maintain part of this site
    when I have time and ideas

**Comment by lowfatcomputing** [comment]
This could be the replacement for the now defunct http://forthfreak.net wiki.

**Comment by larsbrinkhoff** [comment]
Thanks @xieyuheng, that's a great start!

@lowfatcomputing Sorry to hear forthfreat.net is indeed defunct.  I miss it.

**Comment by larsbrinkhoff** [comment]
I created a new wiki:
https://github.com/ForthHub/wiki/wiki

**Comment by xieyuheng** [comment]
in my site
all pages (except the welcome page) are generated by emacs's htmlize.el
the result is faked org-mode buffer

I consider this style is not acceptable (and not maintainable) by other developers
this is why I am not adding more pages

so
if you are good at html and css and js
feel free to re-design the css of the site
and add more contents

**Comment by xieyuheng** [comment]
if no one want to seriously design new css and write html pages,
I can do one of the following ::

1. simply link sections of the welcome page to wiki
2. to use my emacs org-mode css style to generate more pages

any ideas ?

**Comment by DRuffer** [comment]
If you have time and interest, you can make the rules, IMNSHO.


DaR






From: XIE Yuheng
Sent: ‎Saturday‎, ‎April‎ ‎25‎, ‎2015 ‎8‎:‎11‎ ‎AM
To: ForthHub/discussion





if no one want to seriously design new css and write html pages,
I can do one of the following ::
simply link sections of the welcome page to wiki
to use my emacs org-mode css style to generate more pages

any ideas ?

**Comment by lowfatcomputing** [comment]
We could start by porting over some surviving content from http://web.archive.org/web/*/forthfreak.net to http://forthhub.github.io/ 

I think Github Pages provides more flexibility and control over the look of the content than Github Wikis which are designed more for project documentation.

IMHO http://forthhub.github.io should be a living thing, not just an archive.

I can do some of this on the weekend.

**Comment by lowfatcomputing** [comment]
Complete list of surviving URLs: http://web.archive.org/web/*/http://www.forthfreak.net*

**Comment by Bushmills** [comment]
complete archive of all forthfreak wiki pages, plain ASCII, can still be downloaded from http://forthfreak.net/ForthFreakWikiAllInOne.tgz

**Comment by larsbrinkhoff** [comment]
The tgz is now archived here:
http://github.com/ForthHub/ForthFreak

**Comment by larsbrinkhoff** [comment]
http://forthhub.github.io/ looks unmaintained.

If no one is interested in fleshing it out, I suggest we either:
- Delete it, or
- Just as a brief description and a link to http://github.com/ForthHub

**Comment by saulpw** [comment]
I vote for 'delete', with archival if anyone thinks the content is worth preserving.

**Comment by larsbrinkhoff** [comment]
@xieyuheng, do you have any input?

**Comment by xieyuheng** [comment]
Sorry everyone, I fail to maintain this repo.

A much simpler page,
with brief description and a link to http://github.com/ForthHub,
would be much better than the existing one.

I will delete it at first, to clean up the git history of the repo.

**Comment by larsbrinkhoff** [comment]
It has been deleted, so I'll close this issue.
