### ISSUE TITLE
VolksForth

### ISSUE THREAD

**Issue by bodhi-baum** [ForthHub/discussion#98]
I think it would be nice if https://github.com/forth-ev/VolksForth could be added to the list. VF is for various 8bit and 16bit-systems and is heavily developed right now to fit the newest standard.

**Comment by ruv** [comment]
An open list of Forth systems is available in [ForthHub wiki](https://github.com/ForthHub/wiki/wiki/Forth-Systems). You can add VolksForth there.

**Comment by bodhi-baum** [comment]
Done.
